package ru.practicum.shareit.persistence;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class SchemaUpgradeTest {
    @Test
    void upgradesExistingItemsWithoutLosingDataAndCreatesRequestForeignKey() {
        DriverManagerDataSource source = new DriverManagerDataSource(
                "jdbc:h2:mem:upgrade-" + UUID.randomUUID()
                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(source);
        try {
            jdbc.execute("CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(255) NOT NULL, email VARCHAR(512) NOT NULL UNIQUE)");
            jdbc.execute("CREATE TABLE items (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(255) NOT NULL, description VARCHAR(2000) NOT NULL, available BOOLEAN NOT NULL, "
                    + "owner_id BIGINT NOT NULL REFERENCES users(id))");
            jdbc.update("INSERT INTO users (id, name, email) VALUES (1, 'Owner', 'owner@example.com')");
            jdbc.update("INSERT INTO items (id, name, description, available, owner_id) "
                    + "VALUES (1, 'Old item', 'Preserve me', TRUE, 1)");
            ResourceDatabasePopulator schema = new ResourceDatabasePopulator(new ClassPathResource("schema.sql"));
            schema.execute(source);
            schema.execute(source);
            assertEquals("Preserve me", jdbc.queryForObject("SELECT description FROM items WHERE id=1", String.class));
            assertNull(jdbc.queryForObject("SELECT request_id FROM items WHERE id=1", Long.class));
            assertThrows(DataIntegrityViolationException.class,
                    () -> jdbc.update("UPDATE items SET request_id=999 WHERE id=1"));
            jdbc.update("INSERT INTO item_requests (id, description, requester_id, created) VALUES (2, ?, 1, ?)",
                    "Need item", Timestamp.valueOf(LocalDateTime.of(2030, 1, 15, 12, 0)));
            jdbc.update("UPDATE items SET request_id=2 WHERE id=1");
            assertEquals(2L, jdbc.queryForObject("SELECT request_id FROM items WHERE id=1", Long.class));
            jdbc.update("DELETE FROM item_requests WHERE id=2");
            assertNull(jdbc.queryForObject("SELECT request_id FROM items WHERE id=1", Long.class));
        } finally {
            jdbc.execute("SHUTDOWN");
        }
    }
}
